"""Job — Redeemer, trial, restoration"""
from catalog._entry import e

ENTRIES = [
    e('Job', 1, 21, 21, 'Naked I came out of my mother’s womb, and naked I will return there. The LORD gave, and the LORD has taken away. Blessed be the LORD’s name.', 'Job’s worship in loss.', ['faithfulness', 'worship', 'providence'], ['sad', 'bitter', 'hopeful', 'grateful'], ['naked', 'gave', 'taken', 'blessed']),
    e('Job', 5, 17, 18, 'Happy is the man whom God corrects; don’t despise the chastening of the Almighty—for he wounds and binds up; he injures and his hands make whole.', 'Eliphaz (partial truth).', ['healing', 'wisdom', 'compassion'], ['bitter', 'weary', 'hopeful'], ['corrects', 'wounds', 'binds', 'make whole']),
    e('Job', 8, 20, 21, 'God will not cast away a blameless man; he will yet fill your mouth with laughter and your lips with shouting.', 'Bildad’s hope (applied carefully).', ['hope', 'joy', 'justice'], ['sad', 'hopeless', 'hopeful'], ['cast away', 'laughter', 'shouting']),
    e('Job', 11, 13, 15, 'If you set your heart aright and stretch out hands toward him—you will lift up your face without spot; you will be steadfast and not fear.', 'Zophar’s counsel (conditional).', ['fear', 'holiness', 'peace'], ['guilty', 'afraid', 'hopeful'], ['heart', 'face', 'steadfast', 'fear']),
    e('Job', 12, 9, 10, 'Who doesn’t know that the LORD’s hand has done this, in whose hand is the life of every living thing and the breath of all mankind?', 'Job on sovereignty.', ['providence', 'life'], ['confused', 'hopeful'], ['hand', 'life', 'breath']),
    e('Job', 13, 15, 15, 'Behold, he will kill me. I have no hope. Nevertheless, I will maintain my ways before him.', 'Trust amid dread.', ['hope', 'courage', 'faithfulness'], ['afraid', 'hopeless', 'hopeful'], ['kill', 'hope', 'maintain']),
    e('Job', 14, 14, 15, 'If a man dies, will he live again? All the days of my warfare I wait until my release comes. You will call, and I will answer; you will long for the work of your hands.', 'Longing resurrection hint.', ['hope', 'resurrection', 'presence'], ['sad', 'hopeless', 'hopeful'], ['die', 'live', 'call', 'answer', 'long']),
    e('Job', 16, 19, 19, 'Even now my witness is in heaven. He who vouches for me is on high.', 'Heavenly witness.', ['hope', 'justice', 'presence'], ['lonely', 'hopeless', 'hopeful'], ['witness', 'heaven', 'vouches']),
    e('Job', 19, 25, 27, 'I know that my Redeemer lives, and in the end he will stand on the earth; after my skin is destroyed, then in my flesh I will see God.', 'Redeemer lives.', ['hope', 'salvation', 'resurrection', 'eternal-life'], ['sad', 'hopeless', 'hopeful'], ['Redeemer', 'lives', 'see God', 'flesh']),
    e('Job', 22, 21, 23, 'Acquaint yourself with him now and be at peace; thereby good will come. Return to the Almighty and you will be built up.', 'Eliphaz (peace path).', ['peace', 'restoration', 'wisdom'], ['anxious', 'bitter', 'peaceful', 'hopeful'], ['acquaint', 'peace', 'return', 'built up']),
    e('Job', 23, 10, 10, 'But he knows the way that I take. When he has tried me, I will come out like gold.', 'Tried like gold.', ['providence', 'hope', 'holiness'], ['weary', 'confused', 'hopeful'], ['knows', 'tried', 'gold', 'way']),
    e('Job', 23, 13, 14, 'But he stands alone, and who can oppose him? What his soul desires, even that he does. For he performs that which is appointed for me.', 'Appointed purpose.', ['providence', 'sovereignty'], ['confused', 'afraid', 'hopeful'], ['desires', 'performs', 'appointed']),
    e('Job', 33, 27, 28, 'He sings before men: I have sinned; he has redeemed my soul from going into the pit; my life will see the light.', 'Elihu on restoration.', ['forgiveness', 'salvation', 'hope'], ['guilty', 'hopeful', 'grateful'], ['sinned', 'redeemed', 'pit', 'light']),
    e('Job', 36, 7, 7, 'He doesn’t withdraw his eyes from the righteous, but with kings on the throne he sets them forever, and they are exalted.', 'Elihu on God’s eye.', ['presence', 'justice', 'hope'], ['lonely', 'hopeful'], ['eyes', 'righteous', 'throne', 'exalted']),
    e('Job', 36, 15, 16, 'He delivers the afflicted by their affliction and opens their ear in oppression; yes, he would have allured you out of distress into a broad place where there is no constraint.', 'Deliverance through affliction.', ['deliverance', 'wisdom', 'comfort'], ['weary', 'bitter', 'hopeful'], ['afflicted', 'affliction', 'broad place', 'ear']),
    e('Job', 42, 2, 2, 'I know that you can do all things, and that no purpose of yours can be restrained.', 'Job’s confession.', ['providence', 'sovereignty', 'faithfulness'], ['humbled', 'hopeful'], ['all things', 'purpose', 'restrained']),
    e('Job', 42, 10, 10, 'The LORD restored Job’s prosperity when he prayed for his friends. The LORD gave Job twice as much as he had before.', 'Restoration double.', ['restoration', 'compassion', 'blessing'], ['sad', 'bitter', 'hopeful', 'grateful'], ['restored', 'prayed', 'twice', 'prosperity']),
    e('Job', 42, 12, 12, 'So the LORD blessed the latter end of Job more than his beginning—sheep, camels, oxen, and donkeys in abundance.', 'Latter end blessed.', ['blessing', 'restoration', 'provision'], ['hopeful', 'grateful', 'happy'], ['latter end', 'blessed', 'beginning']),
]
