"""Daniel — kingdom, deliverance, resurrection"""
from catalog._entry import e

ENTRIES = [
    e('Daniel', 2, 20, 22, 'Blessed be God’s name forever; he changes times and seasons; he removes kings and sets up kings; he gives wisdom to the wise; he reveals deep and secret things; light dwells with him.', 'Daniel after mystery revealed.', ['wisdom', 'providence', 'sovereignty'], ['confused', 'afraid', 'hopeful', 'grateful'], ['times', 'kings', 'wisdom', 'secret', 'light']),
    e('Daniel', 2, 44, 44, 'In days of those kings the God of heaven will set up a kingdom which will never be destroyed; it will break other kingdoms and stand forever.', 'Everlasting kingdom.', ['kingdom', 'hope', 'victory'], ['afraid', 'hopeless', 'hopeful'], ['kingdom', 'never destroyed', 'forever', 'God of heaven']),
    e('Daniel', 3, 17, 18, 'Our God whom we serve is able to deliver us from the burning fiery furnace; but if not, we won’t serve your gods.', 'Able to deliver (faith stance).', ['deliverance', 'courage', 'faithfulness'], ['afraid', 'hopeful'], ['able', 'deliver', 'furnace', 'but if not']),
    e('Daniel', 3, 24, 25, 'Look, I see four men loose, walking in the fire, and they have no hurt; the aspect of the fourth is like a son of the gods.', 'Presence in the fire.', ['presence', 'protection', 'deliverance'], ['afraid', 'hopeful', 'peaceful'], ['fire', 'fourth', 'walking', 'hurt']),
    e('Daniel', 4, 34, 35, 'I blessed the Most High; his dominion is everlasting; all inhabitants of earth are reputed as nothing; he does according to his will; none can stop his hand or ask, What are you doing?', 'Nebuchadnezzar restored.', ['sovereignty', 'providence'], ['proud', 'humbled', 'hopeful'], ['dominion', 'will', 'stop', 'Most High']),
    e('Daniel', 6, 22, 22, 'My God has sent his angel and has shut the lions’ mouths, and they have not hurt me.', 'Daniel in lions’ den.', ['protection', 'deliverance', 'presence'], ['afraid', 'grateful', 'hopeful'], ['angel', 'lions', 'shut', 'hurt']),
    e('Daniel', 6, 26, 27, 'He is the living God, steadfast forever; his kingdom won’t be destroyed; he delivers and rescues, works signs in heaven and earth; he has delivered Daniel from lions’ power.', 'Darius decree.', ['kingdom', 'deliverance', 'faithfulness'], ['afraid', 'hopeful', 'grateful'], ['living God', 'delivers', 'rescues', 'lions']),
    e('Daniel', 7, 13, 14, 'One like a son of man came with clouds; dominion, glory, kingdom given—all peoples serve him; dominion everlasting, won’t pass away; kingdom won’t be destroyed.', 'Son of Man vision.', ['kingdom', 'hope', 'nations', 'eternal-life'], ['afraid', 'hopeful'], ['son of man', 'clouds', 'dominion', 'everlasting']),
    e('Daniel', 7, 18, 18, 'But the saints of the Most High will receive the kingdom, and possess the kingdom forever, even forever and ever.', 'Saints receive kingdom.', ['kingdom', 'hope', 'eternal-life'], ['hopeless', 'hopeful'], ['saints', 'receive', 'kingdom', 'forever']),
    e('Daniel', 7, 27, 27, 'The kingdom and dominion under whole heaven will be given to people of saints of Most High; kingdom everlasting; all dominions serve and obey.', 'Given to the people.', ['kingdom', 'hope', 'victory'], ['hopeless', 'hopeful'], ['dominion', 'saints', 'everlasting', 'obey']),
    e('Daniel', 9, 9, 9, 'To the Lord our God belong mercies and forgiveness, for we have rebelled against him.', 'Daniel’s confession.', ['mercy', 'forgiveness'], ['guilty', 'hopeful'], ['mercies', 'forgiveness', 'rebelled']),
    e('Daniel', 9, 18, 19, 'We don’t present pleas for our righteousness but for your great mercies. Lord, hear; Lord, forgive; Lord, listen and do; don’t defer for your own sake.', 'Appeal to mercies.', ['mercy', 'forgiveness', 'prayer'], ['guilty', 'hopeless', 'hopeful'], ['mercies', 'forgive', 'hear', 'own sake']),
    e('Daniel', 10, 12, 12, 'Don’t be afraid, Daniel; from the first day you set your heart to understand and humble yourself, your words were heard, and I have come for your words’ sake.', 'Heard from day one.', ['fear', 'prayer', 'presence'], ['afraid', 'anxious', 'hopeful'], ['afraid', 'heard', 'first day', 'humble']),
    e('Daniel', 10, 18, 19, 'One like appearance of a man touched me and strengthened me: Peace be to you. Be strong, be strong. When he spoke, I was strengthened.', 'Touched and strengthened.', ['peace', 'strength', 'presence', 'courage'], ['afraid', 'weary', 'peaceful', 'hopeful'], ['touched', 'peace', 'strong', 'strengthened']),
    e('Daniel', 12, 1, 1, 'At that time Michael will stand up; there will be a time of trouble such as never was; but your people will be delivered, everyone found written in the book.', 'Delivered from trouble.', ['deliverance', 'protection', 'hope'], ['afraid', 'hopeless', 'hopeful'], ['Michael', 'trouble', 'delivered', 'book']),
    e('Daniel', 12, 2, 3, 'Many who sleep in the dust will awake, some to everlasting life; those who are wise will shine as brightness of the expanse; those who turn many to righteousness as the stars forever.', 'Resurrection hope.', ['resurrection', 'eternal-life', 'hope', 'wisdom'], ['sad', 'hopeless', 'hopeful'], ['awake', 'everlasting life', 'shine', 'stars']),
    e('Daniel', 12, 13, 13, 'Go your way until the end; for you will rest, then rise again to receive your inheritance at the end of the days.', 'Daniel’s personal end hope.', ['rest', 'hope', 'resurrection', 'reward'], ['weary', 'hopeful', 'peaceful'], ['rest', 'rise', 'inheritance', 'end']),
]
