"""Hosea promises"""
from catalog._entry import e

ENTRIES = [
    e('Hosea', 1, 10, 10, 'Yet the number of Israel will be as sand of sea; in place where said Not my people, it will be said Sons of the living God.', 'Reversal of Lo-ammi.', ['hope', 'identity', 'covenant', 'offspring'], ['rejected', 'hopeful', 'loved'], ['sand', 'Not my people', 'sons', 'living God']),
    e('Hosea', 2, 14, 15, 'I will allure her and bring her into wilderness and speak comfortably; I will give vineyards from there and Valley of Achor for door of hope; she will respond as in youth.', 'Door of hope.', ['hope', 'restoration', 'love', 'compassion'], ['bitter', 'hopeless', 'loved', 'hopeful'], ['allure', 'wilderness', 'Achor', 'hope', 'vineyards']),
    e('Hosea', 2, 16, 20, 'You will call me My husband; I will betroth you to me forever in righteousness, justice, loving kindness, mercies, and faithfulness; you will know the LORD.', 'Forever betrothal.', ['covenant', 'love', 'faithfulness', 'mercy'], ['lonely', 'ashamed', 'loved', 'hopeful'], ['husband', 'betroth', 'forever', 'know']),
    e('Hosea', 2, 21, 23, 'I will sow her to me in earth; I will have mercy on No Mercy; I will say to Not my people, You are my people; they will say, My God.', 'Mercy restored; my people.', ['mercy', 'identity', 'covenant', 'restoration'], ['rejected', 'hopeless', 'loved', 'hopeful'], ['sow', 'mercy', 'my people', 'My God']),
    e('Hosea', 6, 1, 3, 'Come, let’s return to the LORD; he has torn and will heal; he has injured and will bind up. After two days he will revive; on third day raise up. Let’s press on to know the LORD—his going forth sure as morning; he comes as rain.', 'Return; heal; rain.', ['repentance', 'healing', 'hope', 'restoration'], ['guilty', 'weary', 'hopeful'], ['return', 'heal', 'bind', 'revive', 'rain']),
    e('Hosea', 11, 1, 1, 'When Israel was a child, then I loved him, and called my son out of Egypt.', 'Loved child called (NT cites).', ['love', 'deliverance', 'calling'], ['loved', 'hopeful'], ['child', 'loved', 'son', 'Egypt']),
    e('Hosea', 11, 3, 4, 'I taught Ephraim to walk; I took them on my arms; I drew them with cords of a man, with bands of love; I lifted yoke and laid food before them.', 'Fatherly teaching love.', ['love', 'compassion', 'guidance', 'provision'], ['weary', 'bitter', 'loved', 'hopeful'], ['taught', 'arms', 'bands of love', 'yoke', 'food']),
    e('Hosea', 11, 8, 9, 'How can I give you up, Ephraim? My heart is turned within me; my compassions are kindled. I will not execute fierceness of anger—for I am God and not man, the Holy One among you.', 'Cannot give up.', ['compassion', 'mercy', 'love', 'holiness'], ['guilty', 'afraid', 'loved', 'hopeful'], ['give up', 'heart', 'compassions', 'not man']),
    e('Hosea', 14, 4, 5, 'I will heal their waywardness. I will love them freely; for my anger is turned away. I will be like the dew to Israel; he will blossom like the lily.', 'Heal and freely love.', ['healing', 'love', 'mercy', 'restoration'], ['guilty', 'bitter', 'loved', 'hopeful'], ['heal', 'freely', 'dew', 'blossom', 'lily']),
    e('Hosea', 14, 7, 7, 'Men will rest in his shade; they will revive as grain and blossom as vine.', 'Rest in shade; revive.', ['rest', 'restoration', 'hope'], ['weary', 'hopeless', 'hopeful'], ['shade', 'revive', 'grain', 'vine']),
]
