"""Joel promises"""
from catalog._entry import e

ENTRIES = [
    e('Joel', 2, 12, 13, 'Turn to me with all your heart, with fasting, weeping, mourning; tear your heart and not garments; turn to the LORD—for he is gracious, merciful, slow to anger, abundant in loving kindness, and relents from sending calamity.', 'Tear hearts; gracious God.', ['repentance', 'mercy', 'compassion'], ['guilty', 'afraid', 'hopeful'], ['turn', 'heart', 'gracious', 'relents']),
    e('Joel', 2, 18, 19, 'Then the LORD was jealous for his land and had pity on his people; I will send you grain, new wine, oil, and you will be satisfied; I will no more make you a reproach among nations.', 'Pity and provision.', ['compassion', 'provision', 'restoration'], ['ashamed', 'anxious', 'hopeful', 'grateful'], ['jealous', 'pity', 'grain', 'satisfied']),
    e('Joel', 2, 21, 22, 'Don’t be afraid, land; rejoice—the LORD has done great things. Don’t be afraid, animals—pastures spring, tree bears fruit.', 'Fear not, land.', ['fear', 'joy', 'restoration', 'provision'], ['afraid', 'hopeful', 'happy'], ['afraid', 'rejoice', 'pastures', 'fruit']),
    e('Joel', 2, 23, 24, 'Rejoice in the LORD your God—he gives former rain moderately and rains; threshing floors full of wheat, vats overflow.', 'Rain and overflow.', ['provision', 'joy', 'blessing'], ['anxious', 'hopeful', 'grateful'], ['former rain', 'wheat', 'overflow']),
    e('Joel', 2, 25, 27, 'I will restore to you the years the swarming locust has eaten; you will eat plenty and be satisfied; my people will never be disappointed; you will know I am in midst of Israel.', 'Years restored; not disappointed.', ['restoration', 'provision', 'presence', 'hope'], ['regret', 'hopeless', 'hopeful', 'grateful'], ['restore', 'years', 'locust', 'disappointed', 'midst']),
    e('Joel', 2, 28, 29, 'I will pour out my Spirit on all flesh; sons and daughters prophesy; old dream; young see visions; on servants and handmaids I will pour out my Spirit.', 'Spirit on all flesh (Pentecost).', ['spirit', 'hope', 'nations', 'calling'], ['hopeless', 'hopeful'], ['Spirit', 'all flesh', 'prophesy', 'visions']),
    e('Joel', 2, 32, 32, 'It will happen that whoever will call on the LORD’s name will be saved; for in Mount Zion and Jerusalem there will be those who escape, as the LORD has said, and among the remnant those whom the LORD calls.', 'Call and be saved.', ['salvation', 'hope', 'remnant'], ['afraid', 'hopeless', 'hopeful'], ['call', 'name', 'saved', 'remnant']),
    e('Joel', 3, 16, 17, 'The LORD will roar from Zion; the LORD will be a refuge to his people, a stronghold to Israel. So you will know I am the LORD your God, dwelling in Zion my holy mountain.', 'Refuge and dwelling.', ['protection', 'presence', 'salvation'], ['afraid', 'hopeful'], ['roar', 'refuge', 'stronghold', 'dwelling']),
    e('Joel', 3, 18, 18, 'In that day mountains will drop sweet wine, hills flow with milk, all brooks of Judah flow with waters; a fountain will come from the LORD’s house.', 'Abundance fountain.', ['provision', 'hope', 'presence'], ['hopeful', 'happy'], ['wine', 'milk', 'fountain', 'house']),
]
