"""Micah promises"""
from catalog._entry import e

ENTRIES = [
    e('Micah', 4, 1, 3, 'In latter days mountain of LORD’s house established; nations stream; he teaches ways; they beat swords into plowshares; nation not lift sword; nor learn war anymore.', 'Peace among nations.', ['peace', 'nations', 'wisdom', 'hope'], ['afraid', 'peaceful', 'hopeful'], ['latter days', 'plowshares', 'war', 'nations']),
    e('Micah', 4, 4, 4, 'But every man will sit under his vine and under his fig tree; no one will make them afraid, for the mouth of the LORD of Armies has spoken.', 'Unafraid under vine.', ['peace', 'provision', 'fear', 'promise'], ['afraid', 'anxious', 'peaceful', 'hopeful'], ['vine', 'fig', 'afraid', 'spoken']),
    e('Micah', 4, 5, 5, 'Though all peoples walk each in name of his god, we will walk in the name of the LORD our God forever and ever.', 'Walk in LORD’s name forever.', ['faithfulness', 'identity', 'hope'], ['confused', 'hopeful'], ['walk', 'name', 'forever']),
    e('Micah', 5, 2, 2, 'But you, Bethlehem Ephrathah, though small among Judah’s clans, out of you one will come who is to be ruler in Israel, whose origins are from of old, from ancient days.', 'Bethlehem ruler (NT cites).', ['kingdom', 'hope', 'promise'], ['hopeful'], ['Bethlehem', 'ruler', 'ancient']),
    e('Micah', 5, 4, 5, 'He will stand and shepherd in the LORD’s strength; they will live securely; he will be great to ends of earth. This one will be our peace.', 'Shepherd; our peace.', ['peace', 'protection', 'presence', 'kingdom'], ['afraid', 'anxious', 'peaceful', 'hopeful'], ['shepherd', 'securely', 'peace', 'ends of earth']),
    e('Micah', 6, 8, 8, 'He has shown you, man, what is good: to act justly, to love mercy, and to walk humbly with your God.', 'What God requires.', ['justice', 'mercy', 'humility', 'wisdom'], ['confused', 'guilty', 'hopeful'], ['justly', 'mercy', 'humbly', 'good']),
    e('Micah', 7, 7, 8, 'But as for me, I will look to the LORD. I will wait for the God of my salvation. My God will hear me. Don’t rejoice against me, enemy; when I fall, I will arise; when I sit in darkness, the LORD will be a light to me.', 'Fall and arise; light in darkness.', ['hope', 'salvation', 'light', 'endurance'], ['hopeless', 'sad', 'afraid', 'hopeful'], ['wait', 'hear', 'arise', 'darkness', 'light']),
    e('Micah', 7, 9, 9, 'I will bear the indignation of the LORD because I have sinned; until he pleads my case and executes judgment for me. He will bring me into the light, and I will see his righteousness.', 'Into the light.', ['hope', 'justice', 'forgiveness'], ['guilty', 'hopeless', 'hopeful'], ['indignation', 'pleads', 'light', 'righteousness']),
    e('Micah', 7, 18, 19, 'Who is a God like you, who pardons iniquity and passes over transgression of remnant? He doesn’t retain anger forever, because he delights in loving kindness. He will again have compassion; he will tread our iniquities; cast all sins into depths of sea.', 'Sins into the sea.', ['forgiveness', 'mercy', 'compassion', 'love'], ['guilty', 'shame', 'hopeful', 'loved'], ['pardons', 'loving kindness', 'compassion', 'sea', 'sins']),
    e('Micah', 7, 20, 20, 'You will give truth to Jacob and loving kindness to Abraham, as you have sworn to our fathers from days of old.', 'Sworn truth and kindness.', ['covenant', 'faithfulness', 'mercy'], ['hopeful', 'loved'], ['truth', 'loving kindness', 'sworn', 'Abraham']),
]
