"""Zechariah promises"""
from catalog._entry import e

ENTRIES = [
    e('Zechariah', 1, 3, 3, 'Return to me, says the LORD of Armies, and I will return to you.', 'Return exchange.', ['repentance', 'presence', 'hope'], ['guilty', 'lonely', 'hopeful'], ['return', 'return to you']),
    e('Zechariah', 1, 16, 17, 'I have returned to Jerusalem with mercies; my house will be built; cities will again overflow with prosperity; the LORD will again comfort Zion and choose Jerusalem.', 'Returned with mercies.', ['mercy', 'restoration', 'comfort', 'presence'], ['sad', 'hopeless', 'hopeful'], ['mercies', 'house', 'comfort', 'choose']),
    e('Zechariah', 2, 4, 5, 'Jerusalem will be inhabited as villages without walls; I will be to her a wall of fire around, and I will be the glory in her midst.', 'Wall of fire; glory midst.', ['protection', 'presence', 'glory'], ['afraid', 'hopeful', 'peaceful'], ['wall of fire', 'glory', 'midst', 'walls']),
    e('Zechariah', 2, 8, 9, 'He who touches you touches the apple of his eye; I will shake hand over them; you will know the LORD of Armies has sent me.', 'Apple of his eye.', ['protection', 'love', 'identity'], ['afraid', 'lonely', 'loved', 'hopeful'], ['touches', 'apple', 'eye']),
    e('Zechariah', 2, 10, 11, 'Sing and rejoice, daughter Zion—for I come and I will dwell among you; many nations will join themselves to the LORD and be my people; I will dwell among you.', 'Dwell; nations join.', ['presence', 'nations', 'joy', 'covenant'], ['lonely', 'hopeful', 'happy', 'loved'], ['sing', 'dwell', 'nations', 'my people']),
    e('Zechariah', 3, 4, 5, 'Take the filthy garments off him; I have caused your iniquity to pass from you, and I will clothe you with rich clothing; set a clean turban on his head.', 'Filthy garments removed.', ['forgiveness', 'identity', 'holiness'], ['guilty', 'shame', 'hopeful'], ['filthy', 'iniquity', 'clothe', 'turban']),
    e('Zechariah', 3, 8, 9, 'I will bring my servant, the Branch; I will remove the iniquity of that land in one day.', 'Branch; iniquity removed.', ['salvation', 'forgiveness', 'hope', 'kingdom'], ['guilty', 'hopeful'], ['Branch', 'iniquity', 'one day']),
    e('Zechariah', 4, 6, 6, 'Not by might, nor by power, but by my Spirit, says the LORD of Armies.', 'By my Spirit.', ['spirit', 'strength', 'providence'], ['weary', 'afraid', 'hopeful'], ['might', 'power', 'Spirit']),
    e('Zechariah', 8, 3, 4, 'I have returned to Zion and will dwell in Jerusalem; Jerusalem will be called City of Truth; old men and women sit in streets with staff.', 'Dwell; peaceful age.', ['presence', 'peace', 'restoration'], ['afraid', 'hopeful', 'peaceful'], ['returned', 'dwell', 'Truth', 'old']),
    e('Zechariah', 8, 7, 8, 'I will save my people from east and west; I will bring them; they will dwell in Jerusalem; they will be my people, and I will be their God, in truth and in righteousness.', 'Saved and dwelling.', ['salvation', 'covenant', 'restoration'], ['hopeless', 'hopeful', 'loved'], ['save', 'east', 'west', 'my people', 'truth']),
    e('Zechariah', 8, 12, 13, 'Seed of peace; vine yield fruit; ground increase; heavens dew; remnant possess; as you were a curse among nations, so I will save you and you will be a blessing; don’t be afraid.', 'From curse to blessing.', ['blessing', 'provision', 'fear', 'salvation'], ['ashamed', 'afraid', 'hopeful'], ['peace', 'dew', 'curse', 'blessing', 'afraid']),
    e('Zechariah', 8, 16, 17, 'Speak truth; execute judgment of peace; don’t devise evil; love no false oath—for these I hate.', 'Peaceful justice required.', ['justice', 'peace', 'truth'], ['angry', 'hopeful'], ['truth', 'peace', 'evil', 'oath']),
    e('Zechariah', 9, 9, 10, 'Rejoice greatly, daughter Zion—your king comes to you, righteous and having salvation, lowly riding on donkey; he will speak peace to nations; dominion from sea to sea.', 'King comes; peace to nations (Triumphal Entry).', ['kingdom', 'peace', 'salvation', 'nations', 'humility'], ['hopeless', 'hopeful', 'happy'], ['king', 'donkey', 'peace', 'nations', 'rejoice']),
    e('Zechariah', 9, 11, 12, 'Because of blood of covenant I have set free your prisoners from the pit; return to stronghold, prisoners of hope; even today I declare I will restore double to you.', 'Prisoners of hope; double.', ['hope', 'covenant', 'deliverance', 'restoration'], ['hopeless', 'afraid', 'hopeful'], ['prisoners', 'hope', 'pit', 'double', 'covenant']),
    e('Zechariah', 10, 1, 1, 'Ask of the LORD rain in spring; the LORD who makes storm clouds, and he gives rain showers to everyone for the plants in the field.', 'Ask rain.', ['provision', 'prayer', 'providence'], ['anxious', 'hopeful'], ['rain', 'ask', 'showers', 'field']),
    e('Zechariah', 10, 6, 6, 'I will strengthen house of Judah and save house of Joseph; I will bring them back for I have mercy; they will be as though I hadn’t cast them off; for I am the LORD their God and I will hear them.', 'Strengthen; hear; mercy.', ['strength', 'salvation', 'mercy', 'restoration'], ['rejected', 'hopeless', 'hopeful', 'loved'], ['strengthen', 'mercy', 'cast off', 'hear']),
    e('Zechariah', 12, 1, 1, 'Thus says the LORD who stretches out heavens, lays foundation of earth, and forms spirit of man within him.', 'Creator framing oracle.', ['providence', 'identity'], ['confused', 'hopeful'], ['heavens', 'earth', 'spirit']),
    e('Zechariah', 12, 10, 10, 'I will pour on David’s house and Jerusalem’s inhabitants the spirit of grace and of supplication; they will look to me whom they have pierced; they will mourn.', 'Spirit of grace; pierced (NT).', ['spirit', 'repentance', 'mercy', 'salvation'], ['guilty', 'sad', 'hopeful'], ['spirit', 'grace', 'pierced', 'mourn']),
    e('Zechariah', 13, 1, 1, 'In that day a fountain will be opened to David’s house and Jerusalem’s inhabitants for sin and for uncleanness.', 'Fountain for sin.', ['forgiveness', 'cleansing', 'salvation'], ['guilty', 'shame', 'hopeful'], ['fountain', 'sin', 'uncleanness']),
    e('Zechariah', 13, 9, 9, 'I will bring the third part through fire, refine as silver, try as gold; they will call on my name and I will hear; I will say, It is my people; they will say, The LORD is my God.', 'Refined; heard; my people.', ['covenant', 'prayer', 'holiness', 'identity'], ['weary', 'afraid', 'hopeful', 'loved'], ['refine', 'call', 'hear', 'my people']),
    e('Zechariah', 14, 8, 9, 'Living waters will go out from Jerusalem; the LORD will be King over all the earth; in that day the LORD will be one, and his name one.', 'Living waters; LORD king.', ['kingdom', 'hope', 'nations', 'provision'], ['hopeful'], ['living waters', 'King', 'earth', 'one']),
]
