"""Acts — Spirit, salvation to the nations"""
from catalog._entry import e

ENTRIES = [
    e('Acts', 1, 8, 8, 'You will receive power when the Holy Spirit has come upon you. You will be witnesses to me in Jerusalem, in all Judea and Samaria, and to the uttermost parts of the earth.', 'Ascension commission.', ['spirit', 'calling', 'nations', 'strength'], ['afraid', 'inadequate', 'hopeful'], ['power', 'Holy Spirit', 'witnesses', 'earth']),
    e('Acts', 2, 17, 18, 'In the last days I will pour out my Spirit on all flesh; sons and daughters will prophesy; young men see visions; old men dream; on servants I pour out my Spirit.', 'Pentecost / Joel.', ['spirit', 'hope', 'calling'], ['hopeless', 'hopeful'], ['Spirit', 'all flesh', 'prophesy', 'visions']),
    e('Acts', 2, 21, 21, 'Whoever will call on the name of the Lord will be saved.', 'Call and be saved.', ['salvation', 'hope'], ['afraid', 'guilty', 'hopeless', 'hopeful'], ['call', 'name', 'saved']),
    e('Acts', 2, 38, 39, 'Repent and be baptized in Jesus’ name for forgiveness of sins, and you will receive the Holy Spirit. The promise is to you, your children, and all who are far off—everyone the Lord calls.', 'Forgiveness, Spirit, far off.', ['forgiveness', 'spirit', 'salvation', 'promise'], ['guilty', 'lonely', 'hopeful'], ['repent', 'baptized', 'forgiveness', 'Spirit', 'far off']),
    e('Acts', 3, 19, 21, 'Repent and turn again, that sins may be blotted out and times of refreshing come from the Lord’s presence, until the times of restoration of all things.', 'Refreshing and restoration.', ['repentance', 'forgiveness', 'restoration', 'hope'], ['guilty', 'weary', 'hopeful'], ['blotted', 'refreshing', 'restoration']),
    e('Acts', 4, 12, 12, 'There is salvation in no one else; no other name under heaven given among men by which we must be saved.', 'No other name.', ['salvation', 'identity'], ['afraid', 'confused', 'hopeful'], ['salvation', 'no other', 'name']),
    e('Acts', 10, 34, 35, 'God doesn’t show favoritism; in every nation the one who fears him and works righteousness is acceptable to him.', 'No favoritism.', ['nations', 'justice', 'acceptance'], ['rejected', 'hopeful', 'loved'], ['favoritism', 'nation', 'acceptable']),
    e('Acts', 10, 43, 43, 'Through his name everyone who believes in him receives remission of sins.', 'Remission for believers.', ['forgiveness', 'salvation'], ['guilty', 'hopeful'], ['believes', 'remission', 'name']),
    e('Acts', 13, 38, 39, 'Through this man remission of sins is proclaimed; by him everyone who believes is justified from all things the law of Moses could not justify.', 'Justified from all things.', ['forgiveness', 'salvation'], ['guilty', 'hopeless', 'hopeful'], ['remission', 'justified', 'believes']),
    e('Acts', 16, 31, 31, 'Believe in the Lord Jesus Christ, and you will be saved, you and your household.', 'Jailer and household.', ['salvation', 'hope', 'family'], ['afraid', 'hopeless', 'hopeful'], ['believe', 'saved', 'household']),
    e('Acts', 18, 9, 10, 'Don’t be afraid, but speak and don’t be silent; I am with you, and no one will attack you to harm you, for I have many people in this city.', 'Paul at Corinth.', ['fear', 'presence', 'protection', 'courage'], ['afraid', 'anxious', 'hopeful'], ['afraid', 'with you', 'speak', 'harm']),
    e('Acts', 26, 17, 18, 'I send you to open eyes, turn from darkness to light and from Satan’s power to God, that they may receive remission of sins and an inheritance among the sanctified by faith in me.', 'Paul’s commission.', ['salvation', 'light', 'forgiveness', 'calling', 'inheritance'], ['confused', 'guilty', 'hopeless', 'hopeful'], ['eyes', 'darkness', 'light', 'remission', 'inheritance']),
]
