"""1 Corinthians — wisdom, resurrection, love"""
from catalog._entry import e

ENTRIES = [
    e('1 Corinthians', 1, 8, 9, 'He will also confirm you to the end, blameless in the day of our Lord Jesus Christ. God is faithful, through whom you were called into the fellowship of his Son.', 'Opening thanksgiving.', ['faithfulness', 'calling', 'hope'], ['anxious', 'insecure', 'hopeful'], ['confirm', 'blameless', 'faithful', 'fellowship']),
    e('1 Corinthians', 1, 18, 18, 'The word of the cross is foolishness to those who are dying, but to us who are being saved it is the power of God.', 'Cross as power.', ['salvation', 'strength', 'wisdom'], ['ashamed', 'hopeful'], ['cross', 'power', 'foolishness', 'saved']),
    e('1 Corinthians', 1, 27, 29, 'God chose the foolish, weak, and base things of the world to put to shame the wise and strong—that no flesh should boast before God.', 'God chooses the weak.', ['humility', 'calling', 'identity'], ['inadequate', 'ashamed', 'hopeful', 'loved'], ['chose', 'foolish', 'weak', 'boast']),
    e('1 Corinthians', 2, 9, 10, 'Things which eye didn’t see and ear didn’t hear, and which didn’t enter into the heart of man, God has prepared for those who love him. But to us, God revealed them through the Spirit.', 'Prepared for those who love him.', ['hope', 'spirit', 'love', 'wisdom'], ['hopeful', 'loved'], ['eye', 'ear', 'prepared', 'Spirit', 'love']),
    e('1 Corinthians', 2, 12, 12, 'We received not the spirit of the world, but the Spirit who is from God, that we might know the things that were freely given to us by God.', 'Spirit reveals free gifts.', ['spirit', 'wisdom', 'grace'], ['confused', 'hopeful', 'grateful'], ['Spirit', 'know', 'freely given']),
    e('1 Corinthians', 3, 16, 17, 'Don’t you know that you are God’s temple and that God’s Spirit lives in you? If anyone destroys God’s temple, God will destroy him; for God’s temple is holy, which you are.', 'You are God’s temple.', ['presence', 'spirit', 'holiness', 'identity'], ['lonely', 'insecure', 'hopeful', 'loved'], ['temple', 'Spirit', 'lives', 'holy']),
    e('1 Corinthians', 6, 14, 14, 'God raised up the Lord, and will also raise us up by his power.', 'Will raise us.', ['resurrection', 'hope', 'strength'], ['afraid', 'hopeful'], ['raised', 'raise', 'power']),
    e('1 Corinthians', 6, 19, 20, 'Your body is a temple of the Holy Spirit who is in you, whom you have from God. You are not your own, for you were bought with a price. Therefore glorify God in your body and in your spirit, which are God’s.', 'Bought; Spirit within.', ['spirit', 'identity', 'holiness', 'salvation'], ['guilty', 'insecure', 'hopeful', 'loved'], ['temple', 'bought', 'price', 'glorify']),
    e('1 Corinthians', 10, 13, 13, 'No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape, that you may be able to endure it.', 'Way of escape; faithful God.', ['faithfulness', 'protection', 'endurance', 'strength'], ['tempted', 'afraid', 'weary', 'hopeful'], ['temptation', 'faithful', 'escape', 'endure']),
    e('1 Corinthians', 12, 4, 7, 'There are various kinds of gifts, but the same Spirit; various servings, same Lord; various workings, same God who works all in all. But to each one is given the manifestation of the Spirit for the common good.', 'Gifts for common good.', ['spirit', 'calling', 'unity'], ['inadequate', 'jealous', 'hopeful'], ['gifts', 'Spirit', 'common good']),
    e('1 Corinthians', 13, 4, 8, 'Love is patient and kind; love doesn’t envy; love bears, believes, hopes, and endures all things. Love never fails.', 'Love never fails.', ['love', 'patience', 'hope', 'endurance'], ['bitter', 'jealous', 'lonely', 'loved', 'hopeful'], ['love', 'patient', 'kind', 'never fails', 'endures']),
    e('1 Corinthians', 13, 12, 13, 'Now we see in a mirror, dimly, but then face to face. Now I know in part, but then I will know fully, even as I was also fully known. Now faith, hope, and love remain—these three. The greatest of these is love.', 'Face to face; love greatest.', ['love', 'hope', 'wisdom', 'eternal-life'], ['confused', 'lonely', 'hopeful', 'loved'], ['mirror', 'face to face', 'faith', 'hope', 'love']),
    e('1 Corinthians', 15, 3, 4, 'Christ died for our sins according to the Scriptures, was buried, and was raised on the third day according to the Scriptures.', 'Gospel core.', ['salvation', 'resurrection', 'forgiveness'], ['guilty', 'hopeless', 'hopeful'], ['died', 'sins', 'buried', 'raised', 'third day']),
    e('1 Corinthians', 15, 20, 22, 'But now Christ has been raised from the dead, the first fruits of those who are asleep. For as in Adam all die, so also in Christ all will be made alive.', 'First fruits; made alive.', ['resurrection', 'hope', 'life'], ['sad', 'afraid', 'hopeful'], ['raised', 'first fruits', 'Adam', 'alive']),
    e('1 Corinthians', 15, 51, 52, 'We will not all sleep, but we will all be changed—in a moment, in the twinkling of an eye, at the last trumpet. The trumpet will sound, the dead will be raised incorruptible, and we will be changed.', 'Changed at last trumpet.', ['resurrection', 'hope', 'eternal-life'], ['afraid', 'hopeful'], ['changed', 'trumpet', 'incorruptible', 'twinkling']),
    e('1 Corinthians', 15, 54, 57, 'Death is swallowed up in victory. Death, where is your sting? Thanks be to God, who gives us the victory through our Lord Jesus Christ.', 'Victory over death.', ['victory', 'resurrection', 'gratitude', 'hope'], ['afraid', 'sad', 'hopeful', 'grateful', 'happy'], ['death', 'sting', 'victory', 'thanks']),
    e('1 Corinthians', 15, 58, 58, 'Therefore, my beloved brothers, be steadfast, immovable, always abounding in the Lord’s work, because you know that your labor is not in vain in the Lord.', 'Labor not in vain.', ['hope', 'endurance', 'reward', 'calling'], ['weary', 'hopeless', 'hopeful'], ['steadfast', 'labor', 'vain', 'work']),
    e('1 Corinthians', 16, 13, 14, 'Watch! Stand firm in the faith! Be courageous! Be strong! Let all that you do be done in love.', 'Courage and love.', ['courage', 'strength', 'love'], ['afraid', 'weary', 'hopeful'], ['stand', 'courageous', 'strong', 'love']),
]
