"""2 Corinthians — comfort, new creation, sufficiency"""
from catalog._entry import e

ENTRIES = [
    e('2 Corinthians', 1, 3, 4, 'Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, that we may be able to comfort those who are in any affliction.', 'God of all comfort.', ['comfort', 'compassion', 'mercy'], ['sad', 'weary', 'hopeless', 'hopeful'], ['mercies', 'comfort', 'affliction']),
    e('2 Corinthians', 1, 5, 5, 'For as the sufferings of Christ abound to us, even so our comfort also abounds through Christ.', 'Comfort abounds with suffering.', ['comfort', 'hope'], ['weary', 'suffering', 'hopeful'], ['sufferings', 'comfort', 'abound']),
    e('2 Corinthians', 1, 20, 20, 'For however many are the promises of God, in him is the “Yes.” Therefore also through him is the “Amen,” to the glory of God through us.', 'All God’s promises Yes in Christ.', ['promise', 'faithfulness', 'hope'], ['doubt', 'hopeful'], ['promises', 'Yes', 'Amen']),
    e('2 Corinthians', 1, 21, 22, 'Now he who establishes us with you in Christ and anointed us is God, who also sealed us and gave us the down payment of the Spirit in our hearts.', 'Sealed; Spirit down payment.', ['spirit', 'identity', 'faithfulness', 'hope'], ['insecure', 'hopeful', 'loved'], ['establishes', 'sealed', 'Spirit', 'down payment']),
    e('2 Corinthians', 3, 17, 18, 'Now the Lord is the Spirit; and where the Spirit of the Lord is, there is liberty. We all, with unveiled face seeing the Lord’s glory as in a mirror, are transformed into the same image from glory to glory, even as from the Lord, the Spirit.', 'Liberty; transformed glory to glory.', ['spirit', 'freedom', 'holiness', 'hope'], ['bound', 'weary', 'hopeful'], ['Spirit', 'liberty', 'transformed', 'glory']),
    e('2 Corinthians', 4, 6, 6, 'God, who said, “Light will shine out of darkness,” has shone in our hearts to give the light of the knowledge of the glory of God in the face of Jesus Christ.', 'Light in our hearts.', ['light', 'wisdom', 'presence'], ['confused', 'hopeless', 'hopeful'], ['light', 'darkness', 'hearts', 'glory', 'face']),
    e('2 Corinthians', 4, 7, 9, 'We have this treasure in clay vessels, that the exceeding greatness of the power may be of God, and not from ourselves. We are pressed on every side, yet not crushed; perplexed, yet not to despair; pursued, yet not forsaken; struck down, yet not destroyed.', 'Clay vessels; not crushed or forsaken.', ['strength', 'hope', 'presence', 'endurance'], ['weary', 'hopeless', 'afraid', 'hopeful'], ['clay', 'pressed', 'crushed', 'forsaken', 'destroyed']),
    e('2 Corinthians', 4, 16, 18, 'Therefore we don’t faint. Though our outward person is decaying, yet our inward person is renewed day by day. For our light affliction, which is for the moment, works for us more and more exceedingly an eternal weight of glory.', 'Renewed day by day; eternal weight of glory.', ['hope', 'strength', 'glory', 'endurance'], ['weary', 'sad', 'hopeful'], ['faint', 'renewed', 'affliction', 'glory', 'eternal']),
    e('2 Corinthians', 5, 1, 1, 'For we know that if the earthly house of our tent is dissolved, we have a building from God, a house not made with hands, eternal, in the heavens.', 'Eternal house from God.', ['eternal-life', 'hope'], ['afraid', 'sad', 'hopeful'], ['tent', 'building', 'eternal', 'heavens']),
    e('2 Corinthians', 5, 5, 5, 'Now he who made us for this very thing is God, who also gave to us the down payment of the Spirit.', 'Spirit as down payment.', ['spirit', 'hope', 'faithfulness'], ['anxious', 'hopeful'], ['down payment', 'Spirit']),
    e('2 Corinthians', 5, 7, 7, 'For we walk by faith, not by sight.', 'Walk by faith.', ['faithfulness', 'hope', 'guidance'], ['confused', 'afraid', 'hopeful'], ['walk', 'faith', 'sight']),
    e('2 Corinthians', 5, 17, 17, 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.', 'New creation.', ['new-beginning', 'identity', 'salvation'], ['guilty', 'stuck', 'hopeless', 'hopeful'], ['new creation', 'old', 'passed away', 'new']),
    e('2 Corinthians', 5, 18, 19, 'All things are of God, who reconciled us to himself through Jesus Christ, and gave to us the ministry of reconciliation; namely, that God was in Christ reconciling the world to himself, not reckoning to them their trespasses.', 'Reconciled; trespasses not reckoned.', ['forgiveness', 'salvation', 'peace', 'calling'], ['guilty', 'ashamed', 'hopeful'], ['reconciled', 'trespasses', 'reckoning', 'ministry']),
    e('2 Corinthians', 5, 21, 21, 'For him who knew no sin he made to be sin on our behalf, so that in him we might become the righteousness of God.', 'Became righteousness of God.', ['salvation', 'forgiveness', 'identity'], ['guilty', 'shame', 'hopeful'], ['sin', 'behalf', 'righteousness']),
    e('2 Corinthians', 6, 2, 2, 'Behold, now is the acceptable time. Behold, now is the day of salvation.', 'Now the day of salvation.', ['salvation', 'hope', 'urgency'], ['hopeless', 'hopeful'], ['acceptable', 'day', 'salvation', 'now']),
    e('2 Corinthians', 6, 16, 18, 'I will dwell in them and walk in them. I will be their God, and they will be my people. I will be to you a Father, and you will be to me sons and daughters, says the Lord Almighty.', 'Dwell; Father; sons and daughters.', ['presence', 'covenant', 'identity', 'love'], ['lonely', 'orphaned', 'loved', 'hopeful'], ['dwell', 'walk', 'Father', 'sons', 'daughters']),
    e('2 Corinthians', 7, 6, 6, 'Nevertheless, he who comforts the lowly, God, comforted us by the coming of Titus.', 'God comforts the lowly.', ['comfort', 'compassion'], ['sad', 'lonely', 'hopeful'], ['comforts', 'lowly']),
    e('2 Corinthians', 9, 6, 8, 'He who sows sparingly will also reap sparingly. He who sows bountifully will also reap bountifully. God is able to make all grace abound to you, that you, always having all sufficiency in everything, may abound to every good work.', 'All grace abound; sufficiency.', ['provision', 'grace', 'blessing'], ['anxious', 'money fear', 'hopeful', 'grateful'], ['sows', 'grace', 'abound', 'sufficiency']),
    e('2 Corinthians', 9, 10, 11, 'He who supplies seed to the sower and bread for food will supply and multiply your seed for sowing, and increase the fruits of your righteousness. You will be enriched in everything for all generosity.', 'Supplier multiplies seed.', ['provision', 'blessing', 'compassion'], ['anxious', 'hopeful', 'grateful'], ['seed', 'bread', 'multiply', 'enriched']),
    e('2 Corinthians', 12, 9, 10, 'He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me. When I am weak, then I am strong.', 'Grace sufficient; power in weakness.', ['grace', 'strength', 'humility'], ['weary', 'inadequate', 'hopeless', 'hopeful'], ['grace', 'sufficient', 'weakness', 'power', 'strong']),
    e('2 Corinthians', 13, 11, 11, 'Finally, brothers, rejoice! Be perfected. Be comforted. Be of the same mind. Live in peace, and the God of love and peace will be with you.', 'God of love and peace with you.', ['peace', 'love', 'presence', 'comfort'], ['anxious', 'divided', 'peaceful', 'hopeful'], ['rejoice', 'peace', 'love', 'with you']),
    e('2 Corinthians', 13, 14, 14, 'The grace of the Lord Jesus Christ, the love of God, and the fellowship of the Holy Spirit be with you all.', 'Trinitarian blessing.', ['grace', 'love', 'spirit', 'presence'], ['lonely', 'hopeful', 'loved'], ['grace', 'love', 'fellowship', 'Spirit']),
]
