"""Galatians — freedom, Spirit, sons and heirs"""
from catalog._entry import e

ENTRIES = [
    e('Galatians', 2, 20, 20, 'I have been crucified with Christ, and it is no longer I who live, but Christ lives in me. That life which I now live in the flesh, I live by faith in the Son of God, who loved me and gave himself up for me.', 'Christ lives in me; loved me.', ['identity', 'love', 'salvation', 'presence'], ['guilty', 'lonely', 'loved', 'hopeful'], ['crucified', 'Christ lives', 'loved', 'gave']),
    e('Galatians', 3, 13, 14, 'Christ redeemed us from the curse of the law, having become a curse for us… that the blessing of Abraham might come on the Gentiles through Christ Jesus, that we might receive the promise of the Spirit through faith.', 'Redeemed from curse; Spirit promise.', ['salvation', 'blessing', 'spirit', 'nations'], ['guilty', 'hopeless', 'hopeful'], ['redeemed', 'curse', 'blessing', 'Spirit']),
    e('Galatians', 3, 26, 29, 'You are all children of God, through faith in Christ Jesus. For as many of you as were baptized into Christ have put on Christ. There is neither Jew nor Greek, slave nor free, male nor female; for you are all one in Christ Jesus. If you are Christ’s, then you are Abraham’s offspring and heirs according to promise.', 'Children; one in Christ; heirs.', ['identity', 'covenant', 'unity', 'promise'], ['rejected', 'lonely', 'insecure', 'loved', 'hopeful'], ['children', 'baptized', 'one', 'heirs', 'promise']),
    e('Galatians', 4, 4, 7, 'When the fullness of the time came, God sent out his Son… that we might receive the adoption as children. Because you are children, God sent out the Spirit of his Son into your hearts, crying, “Abba, Father!” So you are no longer a bondservant, but a son; and if a son, then an heir of God through Christ.', 'Adoption; Abba; heir.', ['identity', 'spirit', 'love', 'freedom'], ['orphaned', 'bound', 'afraid', 'loved', 'hopeful'], ['adoption', 'Abba', 'Spirit', 'heir', 'son']),
    e('Galatians', 5, 1, 1, 'Stand firm therefore in the liberty by which Christ has made us free, and don’t be entangled again with a yoke of bondage.', 'Liberty in Christ.', ['freedom', 'salvation', 'courage'], ['bound', 'weary', 'hopeful'], ['liberty', 'free', 'yoke', 'bondage']),
    e('Galatians', 5, 13, 14, 'You were called to freedom… through love be servants to one another. For the whole law is fulfilled in one word, in this: “You shall love your neighbor as yourself.”', 'Freedom to love.', ['freedom', 'love', 'calling'], ['bitter', 'lonely', 'hopeful'], ['freedom', 'love', 'neighbor', 'servants']),
    e('Galatians', 5, 16, 18, 'Walk by the Spirit, and you won’t fulfill the lust of the flesh. If you are led by the Spirit, you are not under the law.', 'Walk by the Spirit.', ['spirit', 'holiness', 'freedom', 'guidance'], ['tempted', 'guilty', 'hopeful'], ['walk', 'Spirit', 'lust', 'led']),
    e('Galatians', 5, 22, 23, 'The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.', 'Fruit of the Spirit.', ['spirit', 'love', 'joy', 'peace'], ['angry', 'anxious', 'bitter', 'hopeful', 'peaceful', 'happy'], ['fruit', 'Spirit', 'love', 'joy', 'peace']),
    e('Galatians', 6, 2, 2, 'Bear one another’s burdens, and so fulfill the law of Christ.', 'Bear burdens.', ['compassion', 'love', 'calling'], ['weary', 'lonely', 'hopeful'], ['bear', 'burdens', 'law of Christ']),
    e('Galatians', 6, 7, 9, 'Don’t be deceived. God is not mocked, for whatever a man sows, that he will also reap. Let’s not be weary in doing good, for we will reap in due season if we don’t give up.', 'Reap in due season; don’t give up.', ['hope', 'endurance', 'reward', 'providence'], ['weary', 'hopeless', 'hopeful'], ['sows', 'reap', 'weary', 'due season', 'give up']),
]
