"""Ephesians — chosen, sealed, armor, love"""
from catalog._entry import e

ENTRIES = [
    e('Ephesians', 1, 3, 6, 'Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly places in Christ—chose us in him before the foundation of the world, that we would be holy and without defect before him in love, having predestined us for adoption as children through Jesus Christ to himself, according to the good pleasure of his will, to the praise of the glory of his grace.', 'Every spiritual blessing; chosen; adoption.', ['blessing', 'identity', 'love', 'calling', 'grace'], ['insecure', 'rejected', 'loved', 'hopeful', 'grateful'], ['blessing', 'chose', 'adoption', 'grace', 'foundation']),
    e('Ephesians', 1, 7, 8, 'In him we have our redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace, which he made to abound toward us.', 'Redemption and forgiveness.', ['forgiveness', 'salvation', 'grace', 'mercy'], ['guilty', 'shame', 'hopeful'], ['redemption', 'blood', 'forgiveness', 'grace']),
    e('Ephesians', 1, 13, 14, 'In him you also, having heard the word of the truth, the Good News of your salvation—in whom, having also believed, you were sealed with the promised Holy Spirit, who is a pledge of our inheritance, to the redemption of God’s own possession, to the praise of his glory.', 'Sealed with Spirit; pledge of inheritance.', ['spirit', 'identity', 'hope', 'inheritance'], ['insecure', 'anxious', 'hopeful', 'loved'], ['sealed', 'Spirit', 'pledge', 'inheritance']),
    e('Ephesians', 2, 4, 7, 'But God, being rich in mercy, for his great love with which he loved us, even when we were dead through our trespasses, made us alive together with Christ—by grace you have been saved—and raised us up with him, and made us to sit with him in the heavenly places in Christ Jesus, that in the ages to come he might show the exceeding riches of his grace in kindness toward us in Christ Jesus.', 'Rich in mercy; made alive; seated with Christ.', ['mercy', 'love', 'salvation', 'grace', 'hope'], ['guilty', 'dead', 'hopeless', 'loved', 'hopeful'], ['mercy', 'loved', 'alive', 'grace', 'seated']),
    e('Ephesians', 2, 8, 10, 'For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast. For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand that we would walk in them.', 'Saved by grace; his workmanship.', ['salvation', 'grace', 'calling', 'identity'], ['guilty', 'inadequate', 'hopeful', 'loved'], ['grace', 'faith', 'gift', 'workmanship', 'good works']),
    e('Ephesians', 2, 13, 14, 'But now in Christ Jesus you who once were far off are made near in the blood of Christ. For he is our peace, who made both one, and broke down the middle wall of separation.', 'Far off made near; he is our peace.', ['peace', 'salvation', 'unity', 'presence'], ['lonely', 'rejected', 'peaceful', 'hopeful', 'loved'], ['far off', 'near', 'peace', 'wall']),
    e('Ephesians', 2, 18, 19, 'For through him we both have our access in one Spirit to the Father. So then you are no longer strangers and foreigners, but you are fellow citizens with the saints and of the household of God.', 'Access to Father; household of God.', ['presence', 'identity', 'spirit', 'unity'], ['lonely', 'rejected', 'loved', 'hopeful'], ['access', 'Spirit', 'Father', 'household', 'strangers']),
    e('Ephesians', 2, 20, 22, 'Being built on the foundation of the apostles and prophets, Christ Jesus himself being the chief cornerstone; in whom the whole building, fitted together, grows into a holy temple in the Lord; in whom you also are built together for a habitation of God in the Spirit.', 'Habitation of God in the Spirit.', ['presence', 'spirit', 'unity', 'holiness'], ['lonely', 'hopeful', 'loved'], ['cornerstone', 'temple', 'habitation', 'Spirit']),
    e('Ephesians', 3, 12, 12, 'In whom we have boldness and access in confidence through our faith in him.', 'Bold access.', ['prayer', 'courage', 'presence'], ['afraid', 'anxious', 'hopeful'], ['boldness', 'access', 'confidence']),
    e('Ephesians', 3, 16, 19, 'That he would grant you, according to the riches of his glory, that you may be strengthened with power through his Spirit in the inner person, that Christ may dwell in your hearts through faith, to the end that you, being rooted and grounded in love, may be strengthened to comprehend with all the saints what is the width and length and height and depth, and to know Christ’s love which surpasses knowledge, that you may be filled with all the fullness of God.', 'Christ dwells; know surpassing love; filled with fullness.', ['love', 'strength', 'spirit', 'presence'], ['lonely', 'weak', 'unloved', 'loved', 'hopeful'], ['strengthened', 'dwell', 'rooted', 'love', 'fullness']),
    e('Ephesians', 3, 20, 21, 'Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us, to him be the glory in the assembly and in Christ Jesus to all generations forever and ever. Amen.', 'Able to do above all we ask or think.', ['providence', 'prayer', 'strength', 'hope'], ['hopeless', 'anxious', 'inadequate', 'hopeful'], ['able', 'abundantly', 'ask', 'think', 'power']),
    e('Ephesians', 4, 4, 6, 'There is one body and one Spirit, even as you also were called in one hope of your calling, one Lord, one faith, one baptism, one God and Father of all, who is over all and through all and in us all.', 'One hope; Father over all.', ['unity', 'hope', 'identity', 'presence'], ['lonely', 'divided', 'hopeful'], ['one', 'hope', 'Father', 'Spirit']),
    e('Ephesians', 4, 22, 24, 'Put away, as concerning your former way of life, the old man that grows corrupt after the lusts of deceit, and be renewed in the spirit of your mind, and put on the new man, who in the likeness of God has been created in righteousness and holiness of truth.', 'New man created in righteousness.', ['new-beginning', 'holiness', 'identity'], ['guilty', 'stuck', 'hopeful'], ['old man', 'renewed', 'new man', 'righteousness']),
    e('Ephesians', 4, 26, 27, '“Be angry, and don’t sin.” Don’t let the sun go down on your wrath, and don’t give place to the devil.', 'Be angry without sin; do not give the devil a foothold.', ['holiness', 'protection', 'wisdom'], ['angry', 'bitter'], ['anger', 'wrath', 'sun', 'devil', 'foothold', 'self-control']),
    e('Ephesians', 4, 32, 32, 'And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you.', 'Forgive as God forgave.', ['forgiveness', 'compassion', 'mercy'], ['bitter', 'angry', 'guilty', 'hopeful'], ['kind', 'forgiving', 'forgave']),
    e('Ephesians', 5, 1, 2, 'Be therefore imitators of God, as beloved children. Walk in love, even as Christ also loved us and gave himself up for us, an offering and a sacrifice to God for a sweet-smelling fragrance.', 'Beloved children; walk in love.', ['love', 'identity', 'calling'], ['lonely', 'bitter', 'loved', 'hopeful'], ['imitators', 'beloved', 'walk', 'love', 'gave']),
    e('Ephesians', 5, 8, 9, 'For you were once darkness, but are now light in the Lord. Walk as children of light, for the fruit of the Spirit is in all goodness and righteousness and truth.', 'Now light in the Lord.', ['light', 'holiness', 'identity', 'spirit'], ['confused', 'guilty', 'hopeful'], ['darkness', 'light', 'children', 'fruit']),
    e('Ephesians', 5, 14, 14, 'Awake, you who sleep, and arise from the dead, and Christ will shine on you.', 'Christ will shine on you.', ['light', 'hope', 'new-beginning'], ['weary', 'hopeless', 'hopeful'], ['awake', 'arise', 'shine']),
    e('Ephesians', 6, 10, 11, 'Finally, be strong in the Lord and in the strength of his might. Put on the whole armor of God, that you may be able to stand against the wiles of the devil.', 'Strong in the Lord; armor.', ['strength', 'protection', 'courage', 'victory'], ['afraid', 'weary', 'hopeful'], ['strong', 'armor', 'stand', 'devil']),
    e('Ephesians', 6, 13, 13, 'Therefore put on the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand.', 'Withstand and stand.', ['protection', 'endurance', 'courage'], ['afraid', 'weary', 'hopeful'], ['armor', 'withstand', 'stand', 'evil day']),
    e('Ephesians', 6, 16, 17, 'Above all, taking up the shield of faith, with which you will be able to quench all the fiery darts of the evil one. And take the helmet of salvation and the sword of the Spirit, which is the word of God.', 'Shield of faith; helmet of salvation.', ['protection', 'salvation', 'spirit', 'faithfulness'], ['afraid', 'anxious', 'hopeful'], ['shield', 'faith', 'helmet', 'salvation', 'sword', 'Spirit']),
]
