"""Philippians — joy, peace, provision"""
from catalog._entry import e

ENTRIES = [
    e('Philippians', 1, 6, 6, 'Being confident of this very thing, that he who began a good work in you will complete it until the day of Jesus Christ.', 'He will complete the good work.', ['faithfulness', 'hope', 'calling'], ['weary', 'insecure', 'hopeful'], ['began', 'complete', 'good work']),
    e('Philippians', 1, 21, 21, 'For to me to live is Christ, and to die is gain.', 'To live is Christ; to die is gain.', ['life', 'hope', 'eternal-life'], ['afraid', 'hopeful'], ['live', 'Christ', 'die', 'gain']),
    e('Philippians', 2, 13, 13, 'For it is God who works in you both to will and to work for his good pleasure.', 'God works in you to will and work.', ['providence', 'calling', 'strength'], ['inadequate', 'weary', 'hopeful'], ['works', 'will', 'work', 'pleasure']),
    e('Philippians', 3, 20, 21, 'For our citizenship is in heaven, from where we also wait for a Savior, the Lord Jesus Christ, who will change the body of our humiliation to be conformed to the body of his glory, according to the working by which he is able even to subject all things to himself.', 'Citizenship in heaven; glorious body.', ['hope', 'eternal-life', 'resurrection', 'identity'], ['weary', 'afraid', 'hopeful'], ['citizenship', 'heaven', 'change', 'glory']),
    e('Philippians', 4, 4, 5, 'Rejoice in the Lord always! Again I will say, Rejoice! Let your gentleness be known to all men. The Lord is at hand.', 'Rejoice; Lord at hand.', ['joy', 'presence', 'peace'], ['sad', 'anxious', 'hopeful', 'happy'], ['rejoice', 'gentleness', 'at hand']),
    e('Philippians', 4, 6, 7, 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.', 'Don’t be anxious; peace will guard.', ['peace', 'prayer', 'fear'], ['anxious', 'afraid', 'peaceful', 'hopeful'], ['anxious', 'prayer', 'thanksgiving', 'peace', 'guard']),
    e('Philippians', 4, 8, 9, 'Whatever things are true, honorable, just, pure, lovely, of good report… think about these things. The things which you learned… do these things, and the God of peace will be with you.', 'God of peace with you.', ['peace', 'wisdom', 'presence'], ['anxious', 'confused', 'peaceful', 'hopeful'], ['true', 'think', 'God of peace', 'with you']),
    e('Philippians', 4, 11, 13, 'I have learned in whatever state I am, to be content in it. I know how to be humbled, and I also know how to abound. I can do all things through Christ who strengthens me.', 'Content; Christ strengthens.', ['strength', 'peace', 'provision'], ['anxious', 'weary', 'inadequate', 'hopeful', 'peaceful'], ['content', 'abound', 'all things', 'strengthens']),
    e('Philippians', 4, 19, 19, 'My God will supply every need of yours according to his riches in glory in Christ Jesus.', 'God will supply every need.', ['provision', 'faithfulness', 'providence'], ['anxious', 'money fear', 'hopeful', 'grateful'], ['supply', 'every need', 'riches', 'glory']),
]
