"""Colossians — fullness in Christ, new self"""
from catalog._entry import e

ENTRIES = [
    e('Colossians', 1, 11, 12, 'Strengthened with all power, according to the might of his glory, for all endurance and perseverance with joy, giving thanks to the Father, who made us fit to be partakers of the inheritance of the saints in light.', 'Strengthened; inheritance in light.', ['strength', 'joy', 'inheritance', 'hope'], ['weary', 'hopeless', 'hopeful', 'grateful'], ['strengthened', 'endurance', 'inheritance', 'light']),
    e('Colossians', 1, 13, 14, 'Who delivered us out of the power of darkness, and translated us into the Kingdom of the Son of his love, in whom we have our redemption, the forgiveness of our sins.', 'Delivered into Son’s kingdom; forgiveness.', ['deliverance', 'salvation', 'forgiveness', 'kingdom', 'love'], ['afraid', 'guilty', 'hopeless', 'hopeful'], ['darkness', 'Kingdom', 'redemption', 'forgiveness']),
    e('Colossians', 1, 19, 20, 'For all the fullness was pleased to dwell in him, and through him to reconcile all things to himself, by him, whether things on the earth or things in the heavens, having made peace through the blood of his cross.', 'Fullness; reconcile; peace by cross.', ['peace', 'salvation', 'reconciliation'], ['guilty', 'anxious', 'peaceful', 'hopeful'], ['fullness', 'reconcile', 'peace', 'cross', 'blood']),
    e('Colossians', 1, 21, 22, 'You, being in past times alienated and enemies in your mind in your evil deeds, yet now he has reconciled in the body of his flesh through death, to present you holy and without defect and blameless before him.', 'Reconciled; presented holy.', ['forgiveness', 'holiness', 'salvation', 'identity'], ['guilty', 'ashamed', 'hopeful'], ['alienated', 'reconciled', 'holy', 'blameless']),
    e('Colossians', 1, 27, 27, 'To whom God was pleased to make known what are the riches of the glory of this mystery among the Gentiles, which is Christ in you, the hope of glory.', 'Christ in you, the hope of glory.', ['hope', 'presence', 'identity', 'glory'], ['lonely', 'hopeless', 'hopeful', 'loved'], ['Christ in you', 'hope', 'glory', 'mystery']),
    e('Colossians', 2, 6, 7, 'As therefore you received Christ Jesus the Lord, walk in him, rooted and built up in him and established in the faith, even as you were taught, abounding in it in thanksgiving.', 'Rooted and built up in him.', ['faithfulness', 'guidance', 'gratitude'], ['confused', 'anxious', 'hopeful', 'grateful'], ['walk', 'rooted', 'built', 'thanksgiving']),
    e('Colossians', 2, 9, 10, 'For in him all the fullness of the Deity dwells bodily, and in him you are made full, who is the head of all principality and power.', 'In him you are made full.', ['identity', 'presence', 'strength'], ['inadequate', 'empty', 'hopeful', 'loved'], ['fullness', 'made full', 'Deity']),
    e('Colossians', 2, 13, 14, 'You were dead through your trespasses and the uncircumcision of your flesh. He made you alive together with him, having forgiven us all our trespasses, wiping out the handwriting in ordinances that was against us. He has taken it out of the way, nailing it to the cross.', 'Made alive; handwriting nailed to cross.', ['forgiveness', 'salvation', 'new-beginning', 'victory'], ['guilty', 'condemned', 'hopeful'], ['dead', 'alive', 'forgiven', 'handwriting', 'cross']),
    e('Colossians', 3, 1, 4, 'If then you were raised together with Christ, seek the things that are above, where Christ is, seated on the right hand of God. Set your mind on the things that are above, not on the things that are on the earth. For you died, and your life is hidden with Christ in God. When Christ, our life, is revealed, then you will also be revealed with him in glory.', 'Life hidden with Christ; revealed in glory.', ['hope', 'identity', 'glory', 'eternal-life'], ['anxious', 'afraid', 'hopeful'], ['raised', 'above', 'hidden', 'glory', 'life']),
    e('Colossians', 3, 12, 15, 'Put on, as God’s chosen ones, holy and beloved, a heart of compassion, kindness, lowliness, humility, and perseverance; bearing with one another, and forgiving each other… even as Christ forgave you, so you also do. Above all these things, walk in love, which is the bond of perfection. And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.', 'Chosen, holy, beloved; peace rule; love.', ['love', 'peace', 'forgiveness', 'identity', 'compassion'], ['bitter', 'angry', 'anxious', 'loved', 'peaceful', 'hopeful'], ['chosen', 'beloved', 'forgiving', 'peace', 'rule', 'love']),
    e('Colossians', 3, 16, 17, 'Let the word of Christ dwell in you richly; in all wisdom teaching and admonishing one another with psalms, hymns, and spiritual songs, singing with grace in your heart to the Lord. Whatever you do, in word or in deed, do all in the name of the Lord Jesus, giving thanks to God the Father through him.', 'Word dwell richly; all in Jesus’ name.', ['wisdom', 'gratitude', 'presence', 'calling'], ['confused', 'weary', 'hopeful', 'grateful'], ['word', 'dwell', 'psalms', 'thanks', 'name']),
]
