"""1 Thessalonians — coming of the Lord, sanctification"""
from catalog._entry import e

ENTRIES = [
    e('1 Thessalonians', 1, 4, 5, 'We know, brothers loved by God, that you are chosen, and that our Good News came to you not in word only, but also in power, and in the Holy Spirit and with much assurance.', 'Loved and chosen; Spirit power.', ['love', 'calling', 'spirit', 'identity'], ['insecure', 'loved', 'hopeful'], ['loved', 'chosen', 'power', 'Spirit']),
    e('1 Thessalonians', 3, 12, 13, 'May the Lord make you to increase and abound in love toward one another and toward all men… to the end he may establish your hearts blameless in holiness before our God and Father at the coming of our Lord Jesus with all his saints.', 'Abound in love; hearts established.', ['love', 'holiness', 'hope'], ['lonely', 'anxious', 'hopeful', 'loved'], ['abound', 'love', 'establish', 'holiness', 'coming']),
    e('1 Thessalonians', 4, 13, 14, 'We don’t want you to be ignorant, brothers, concerning those who have fallen asleep, so that you don’t grieve like the rest, who have no hope. For if we believe that Jesus died and rose again, even so God will bring with him those who have fallen asleep in Jesus.', 'Grief with hope; God will bring them.', ['hope', 'resurrection', 'comfort'], ['sad', 'grieving', 'hopeless', 'hopeful'], ['asleep', 'grieve', 'hope', 'rose', 'bring']),
    e('1 Thessalonians', 4, 16, 18, 'For the Lord himself will descend from heaven with a shout, with the voice of the archangel and with God’s trumpet. The dead in Christ will rise first, then we who are alive… will be caught up together with them in the clouds to meet the Lord in the air. So we will be with the Lord forever. Therefore comfort one another with these words.', 'Caught up; with the Lord forever.', ['hope', 'resurrection', 'comfort', 'eternal-life', 'presence'], ['sad', 'afraid', 'hopeful'], ['descend', 'trumpet', 'caught up', 'forever', 'comfort']),
    e('1 Thessalonians', 5, 9, 10, 'For God didn’t appoint us to wrath, but to the obtaining of salvation through our Lord Jesus Christ, who died for us, that, whether we wake or sleep, we should live together with him.', 'Appointed to salvation; live with him.', ['salvation', 'presence', 'hope'], ['afraid', 'hopeful'], ['wrath', 'salvation', 'live', 'together']),
    e('1 Thessalonians', 5, 16, 18, 'Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you.', 'Rejoice, pray, give thanks.', ['joy', 'prayer', 'gratitude'], ['sad', 'anxious', 'hopeful', 'grateful'], ['rejoice', 'pray', 'thanks', 'will']),
    e('1 Thessalonians', 5, 23, 24, 'May the God of peace himself sanctify you completely. May your whole spirit, soul, and body be preserved blameless at the coming of our Lord Jesus Christ. He who calls you is faithful, who will also do it.', 'Faithful caller will do it.', ['peace', 'holiness', 'faithfulness', 'hope'], ['anxious', 'insecure', 'hopeful', 'peaceful'], ['sanctify', 'preserved', 'faithful', 'will also do']),
]
