"""1 Timothy — mediator, contentment, fight of faith"""
from catalog._entry import e

ENTRIES = [
    e('1 Timothy', 1, 14, 15, 'The grace of our Lord abounded exceedingly with faith and love which is in Christ Jesus. The saying is faithful and worthy of all acceptance, that Christ Jesus came into the world to save sinners, of whom I am chief.', 'Christ came to save sinners.', ['salvation', 'grace', 'mercy', 'love'], ['guilty', 'shame', 'hopeful'], ['grace', 'save', 'sinners', 'faithful saying']),
    e('1 Timothy', 2, 3, 6, 'This is good and acceptable in the sight of God our Savior, who desires all people to be saved and come to full knowledge of the truth. For there is one God and one mediator between God and men, the man Christ Jesus, who gave himself as a ransom for all.', 'Desires all saved; one mediator; ransom.', ['salvation', 'mercy', 'nations'], ['hopeless', 'guilty', 'hopeful'], ['desires', 'saved', 'mediator', 'ransom']),
    e('1 Timothy', 4, 8, 10, 'Godliness is profitable for all things, having promise of the life which is now and of that which is to come. For to this end we both labor and suffer reproach, because we have set our trust in the living God, who is the Savior of all men, especially of those who believe.', 'Promise of life now and to come.', ['hope', 'life', 'salvation', 'faithfulness'], ['weary', 'hopeful'], ['godliness', 'promise', 'life', 'Savior']),
    e('1 Timothy', 6, 6, 8, 'But godliness with contentment is great gain. For we brought nothing into the world, and we certainly can’t carry anything out. But having food and clothing, we will be content with that.', 'Godliness with contentment.', ['peace', 'provision', 'wisdom'], ['anxious', 'jealous', 'peaceful', 'hopeful'], ['contentment', 'gain', 'food', 'clothing']),
    e('1 Timothy', 6, 12, 12, 'Fight the good fight of faith. Take hold of the eternal life to which you were called, and you confessed the good confession in the sight of many witnesses.', 'Take hold of eternal life.', ['eternal-life', 'calling', 'courage'], ['weary', 'afraid', 'hopeful'], ['fight', 'faith', 'eternal life', 'called']),
    e('1 Timothy', 6, 17, 19, 'Charge those who are rich… that they not be arrogant, nor have their hope set on the uncertainty of riches, but on the living God, who richly provides us with everything to enjoy… laying up for themselves a good foundation against the time to come, that they may lay hold of eternal life.', 'Hope on living God who richly provides.', ['provision', 'hope', 'eternal-life'], ['anxious', 'money fear', 'hopeful', 'grateful'], ['riches', 'living God', 'provides', 'enjoy', 'eternal life']),
]
