"""2 Timothy — power, Scripture, crown"""
from catalog._entry import e

ENTRIES = [
    e('2 Timothy', 1, 7, 7, 'For God didn’t give us a spirit of fear, but of power, love, and self-control.', 'Not spirit of fear.', ['fear', 'strength', 'love', 'spirit'], ['afraid', 'anxious', 'hopeful'], ['spirit', 'fear', 'power', 'love', 'self-control']),
    e('2 Timothy', 1, 9, 10, 'Who saved us and called us with a holy calling, not according to our works, but according to his own purpose and grace, which was given to us in Christ Jesus before times eternal, but has now been revealed by the appearing of our Savior, Christ Jesus, who abolished death, and brought life and immortality to light through the Good News.', 'Saved and called by grace; abolished death.', ['salvation', 'calling', 'grace', 'eternal-life', 'victory'], ['guilty', 'afraid', 'hopeful'], ['saved', 'called', 'grace', 'abolished', 'death', 'immortality']),
    e('2 Timothy', 1, 12, 12, 'For this cause I also suffer these things. Yet I am not ashamed, for I know him whom I have believed, and I am persuaded that he is able to guard that which I have committed to him against that day.', 'He is able to guard what I committed.', ['faithfulness', 'protection', 'hope'], ['afraid', 'suffering', 'hopeful'], ['ashamed', 'believed', 'able', 'guard', 'committed']),
    e('2 Timothy', 2, 11, 13, 'Faithful is the saying: For if we died with him, we will also live with him. If we endure, we will also reign with him. If we deny him, he also will deny us. If we are faithless, he remains faithful; for he can’t deny himself.', 'He remains faithful.', ['faithfulness', 'hope', 'eternal-life', 'endurance'], ['weary', 'doubt', 'hopeful'], ['died', 'live', 'endure', 'reign', 'faithful']),
    e('2 Timothy', 2, 19, 19, 'However, God’s firm foundation stands, having this seal: “The Lord knows those who are his,” and, “Let every one who names the name of the Lord depart from unrighteousness.”', 'The Lord knows those who are his.', ['identity', 'faithfulness', 'holiness'], ['insecure', 'lonely', 'hopeful', 'loved'], ['foundation', 'knows', 'his', 'seal']),
    e('2 Timothy', 3, 15, 17, 'From infancy you have known the holy Scriptures which are able to make you wise for salvation through faith which is in Christ Jesus. Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness, that each person who belongs to God may be complete, thoroughly equipped for every good work.', 'Scriptures make wise for salvation; equip.', ['wisdom', 'salvation', 'guidance'], ['confused', 'inadequate', 'hopeful'], ['Scriptures', 'wise', 'salvation', 'God-breathed', 'equipped']),
    e('2 Timothy', 4, 7, 8, 'I have fought the good fight. I have finished the course. I have kept the faith. From now on, the crown of righteousness is stored up for me, which the Lord, the righteous judge, will give to me on that day; and not to me only, but also to all those who have loved his appearing.', 'Crown of righteousness for all who love his appearing.', ['reward', 'hope', 'faithfulness', 'endurance'], ['weary', 'hopeful'], ['fought', 'finished', 'crown', 'appearing']),
    e('2 Timothy', 4, 17, 18, 'But the Lord stood by me and strengthened me… The Lord will deliver me from every evil work and will preserve me for his heavenly Kingdom. To him be the glory forever and ever. Amen.', 'Lord stood by; will preserve for kingdom.', ['presence', 'strength', 'deliverance', 'protection', 'kingdom'], ['afraid', 'lonely', 'weary', 'hopeful'], ['stood by', 'strengthened', 'deliver', 'preserve', 'Kingdom']),
]
