"""James — wisdom, nearness, healing prayer"""
from catalog._entry import e

ENTRIES = [
    e('James', 1, 2, 4, 'Count it all joy, my brothers, when you fall into various temptations, knowing that the testing of your faith produces endurance. Let endurance have its perfect work, that you may be perfect and complete, lacking in nothing.', 'Testing produces endurance; lacking nothing.', ['joy', 'endurance', 'wisdom', 'hope'], ['weary', 'suffering', 'hopeful'], ['joy', 'temptations', 'testing', 'endurance', 'complete']),
    e('James', 1, 5, 6, 'But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him. But let him ask in faith, without any doubting.', 'Ask wisdom; God gives liberally.', ['wisdom', 'prayer', 'providence'], ['confused', 'anxious', 'hopeful'], ['wisdom', 'ask', 'liberally', 'faith']),
    e('James', 1, 12, 12, 'Blessed is a person who endures temptation, for when he has been approved, he will receive the crown of life which the Lord promised to those who love him.', 'Crown of life promised to those who love him.', ['blessing', 'reward', 'endurance', 'love', 'promise'], ['weary', 'tempted', 'hopeful'], ['endures', 'crown', 'life', 'promised', 'love']),
    e('James', 1, 17, 18, 'Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom can be no variation nor turning shadow. Of his own will he gave birth to us by the word of truth, that we should be a kind of first fruits of his creatures.', 'Every good gift; Father of lights; birth by word.', ['providence', 'faithfulness', 'identity', 'new-beginning'], ['anxious', 'grateful', 'hopeful'], ['good gift', 'Father', 'lights', 'birth', 'word']),
    e('James', 1, 19, 20, 'So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger; for the anger of man doesn’t produce the righteousness of God.', 'Swift to hear, slow to speak and anger.', ['wisdom', 'holiness', 'peace'], ['angry', 'bitter'], ['swift', 'hear', 'slow', 'speak', 'anger', 'righteousness']),
    e('James', 2, 5, 5, 'Listen, my beloved brothers. Didn’t God choose those who are poor in this world to be rich in faith and heirs of the Kingdom which he promised to those who love him?', 'Heirs of the Kingdom promised to lovers of God.', ['kingdom', 'promise', 'love', 'identity'], ['poor', 'rejected', 'hopeful', 'loved'], ['choose', 'poor', 'rich', 'heirs', 'Kingdom', 'love']),
    e('James', 2, 12, 13, 'So speak and so do as men who are to be judged by the law of freedom. For judgment is without mercy to him who has shown no mercy. Mercy triumphs over judgment.', 'Mercy triumphs over judgment.', ['mercy', 'justice', 'freedom'], ['bitter', 'angry', 'hopeful'], ['freedom', 'mercy', 'judgment', 'triumphs']),
    e('James', 4, 6, 8, 'But he gives more grace. Therefore it says, “God resists the proud, but gives grace to the humble.” Be subject therefore to God. Resist the devil, and he will flee from you. Draw near to God, and he will draw near to you.', 'More grace; draw near and he draws near.', ['grace', 'humility', 'presence', 'victory'], ['proud', 'lonely', 'tempted', 'hopeful'], ['grace', 'humble', 'resist', 'flee', 'draw near']),
    e('James', 4, 10, 10, 'Humble yourselves in the sight of the Lord, and he will exalt you.', 'Humble; he will exalt.', ['humility', 'hope'], ['ashamed', 'proud', 'hopeful'], ['humble', 'exalt']),
    e('James', 5, 7, 8, 'Be patient therefore, brothers, until the coming of the Lord. Behold, the farmer waits for the precious fruit of the earth, being patient over it, until it receives the early and late rain. You also be patient. Establish your hearts, for the coming of the Lord is at hand.', 'Patient until the Lord’s coming.', ['patience', 'hope'], ['weary', 'impatient', 'hopeful'], ['patient', 'farmer', 'coming', 'establish']),
    e('James', 5, 11, 11, 'Behold, we call them blessed who endured. You have heard of the perseverance of Job and have seen the Lord in the outcome, and how the Lord is full of compassion and mercy.', 'Lord full of compassion and mercy.', ['compassion', 'mercy', 'endurance', 'hope'], ['weary', 'bitter', 'hopeful'], ['endured', 'Job', 'compassion', 'mercy']),
    e('James', 5, 13, 16, 'Is any among you suffering? Let him pray. Is any cheerful? Let him sing praises. Is any among you sick? Let him call for the elders of the assembly, and let them pray over him, anointing him with oil in the name of the Lord. The prayer of faith will heal him who is sick, and the Lord will raise him up. If he has committed sins, he will be forgiven. Confess your sins to one another and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective.', 'Prayer of faith; healing; forgiveness.', ['prayer', 'healing', 'forgiveness', 'compassion'], ['sick', 'weary', 'guilty', 'hopeful'], ['suffering', 'pray', 'sick', 'heal', 'forgiven', 'confess']),
]
