"""1 Peter — living hope, inheritance, casting cares"""
from catalog._entry import e

ENTRIES = [
    e('1 Peter', 1, 3, 5, 'Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy became our father again to a living hope through the resurrection of Jesus Christ from the dead, to an incorruptible and undefiled inheritance that doesn’t fade away, reserved in Heaven for you, who by the power of God are guarded through faith for a salvation ready to be revealed in the last time.', 'Living hope; guarded inheritance.', ['hope', 'mercy', 'salvation', 'inheritance', 'protection'], ['hopeless', 'afraid', 'hopeful', 'grateful'], ['mercy', 'living hope', 'inheritance', 'guarded', 'salvation']),
    e('1 Peter', 1, 6, 7, 'In this you greatly rejoice, though now for a little while, if need be, you have been grieved in various trials, that the proof of your faith, which is more precious than gold that perishes even though it is tested by fire, may be found to result in praise, glory, and honor at the revelation of Jesus Christ.', 'Trials prove faith; praise at revelation.', ['hope', 'endurance', 'faithfulness'], ['sad', 'weary', 'suffering', 'hopeful'], ['trials', 'faith', 'gold', 'fire', 'praise']),
    e('1 Peter', 1, 8, 9, 'Whom, not having known, you love. In him, though now you don’t see him, yet believing, you rejoice greatly with joy that is unspeakable and full of glory, receiving the result of your faith, the salvation of your souls.', 'Joy unspeakable; salvation of souls.', ['joy', 'salvation', 'love', 'hope'], ['sad', 'hopeful', 'happy', 'loved'], ['love', 'believe', 'joy', 'unspeakable', 'salvation']),
    e('1 Peter', 1, 18, 19, 'Knowing that you were redeemed, not with corruptible things with silver or gold, from the useless way of life handed down from your fathers, but with precious blood, as of a lamb without blemish or spot, the blood of Christ.', 'Redeemed with precious blood.', ['salvation', 'forgiveness'], ['guilty', 'hopeful', 'grateful'], ['redeemed', 'blood', 'lamb', 'precious']),
    e('1 Peter', 1, 23, 25, 'Having been born again, not of corruptible seed, but of incorruptible, through the word of God, which lives and remains forever. For all flesh is like grass… but the Lord’s word endures forever. This is the word of Good News which was preached to you.', 'Born again by enduring word.', ['new-beginning', 'faithfulness', 'salvation'], ['hopeless', 'hopeful'], ['born again', 'word', 'endures', 'forever']),
    e('1 Peter', 2, 4, 6, 'Coming to him, a living stone, rejected indeed by men, but chosen by God, precious. You also as living stones are built up as a spiritual house, to be a holy priesthood… Because it is contained in Scripture, “Behold, I lay in Zion a chief cornerstone, chosen and precious: He who believes in him will not be disappointed.”', 'Living stones; not disappointed.', ['identity', 'hope', 'calling', 'faithfulness'], ['rejected', 'lonely', 'hopeful', 'loved'], ['living stone', 'cornerstone', 'believes', 'disappointed']),
    e('1 Peter', 2, 9, 10, 'But you are a chosen race, a royal priesthood, a holy nation, a people for God’s own possession, that you may proclaim the excellence of him who called you out of darkness into his marvelous light. Who in time past were no people, but now are God’s people, who had not obtained mercy, but now have obtained mercy.', 'Chosen; God’s people; obtained mercy.', ['identity', 'calling', 'mercy', 'light'], ['rejected', 'lonely', 'ashamed', 'loved', 'hopeful'], ['chosen', 'priesthood', 'possession', 'light', 'mercy']),
    e('1 Peter', 2, 24, 25, 'He himself bore our sins in his body on the tree, that we, having died to sins, might live to righteousness. You were healed by his wounds. For you were going astray like sheep, but now you have returned to the Shepherd and Overseer of your souls.', 'Bore sins; healed by wounds; returned to Shepherd.', ['salvation', 'healing', 'forgiveness', 'guidance'], ['guilty', 'lost', 'weary', 'hopeful'], ['bore', 'sins', 'healed', 'wounds', 'Shepherd']),
    e('1 Peter', 3, 8, 9, 'Finally, all of you be like-minded, compassionate, loving as brothers, tenderhearted, courteous, not rendering evil for evil or insult for insult; but instead blessing, knowing that you were called to this, that you may inherit a blessing.', 'Called to bless; inherit a blessing.', ['blessing', 'compassion', 'love', 'calling'], ['angry', 'bitter', 'hopeful'], ['compassionate', 'blessing', 'inherit']),
    e('1 Peter', 3, 12, 12, 'For the eyes of the Lord are on the righteous, and his ears open to their prayer; but the face of the Lord is against those who do evil.', 'Eyes on righteous; ears open to prayer.', ['presence', 'prayer', 'justice'], ['lonely', 'anxious', 'hopeful'], ['eyes', 'ears', 'prayer', 'righteous']),
    e('1 Peter', 3, 18, 18, 'Because Christ also suffered for sins once, the righteous for the unrighteous, that he might bring you to God, being put to death in the flesh, but made alive in the Spirit.', 'Righteous for unrighteous; bring you to God.', ['salvation', 'forgiveness', 'presence'], ['guilty', 'lonely', 'hopeful'], ['suffered', 'righteous', 'unrighteous', 'bring', 'God']),
    e('1 Peter', 4, 12, 13, 'Beloved, don’t be astonished at the fiery trial which has come upon you to test you, as though a strange thing happened to you. But because you are partakers of Christ’s sufferings, rejoice, that at the revelation of his glory you also may rejoice with exceeding joy.', 'Share sufferings; rejoice at glory’s revelation.', ['hope', 'joy', 'endurance'], ['suffering', 'afraid', 'hopeful'], ['fiery', 'trial', 'sufferings', 'glory', 'rejoice']),
    e('1 Peter', 4, 19, 19, 'Therefore let them also who suffer according to the will of God in doing good entrust their souls to him, as to a faithful Creator.', 'Entrust to faithful Creator.', ['faithfulness', 'providence', 'endurance'], ['suffering', 'afraid', 'hopeful'], ['suffer', 'entrust', 'faithful', 'Creator']),
    e('1 Peter', 5, 6, 7, 'Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time, casting all your worries on him, because he cares for you.', 'Cast worries; he cares for you.', ['humility', 'comfort', 'providence', 'peace'], ['anxious', 'worried', 'weary', 'hopeful', 'loved'], ['humble', 'exalt', 'worries', 'cares']),
    e('1 Peter', 5, 8, 10, 'Be sober and self-controlled. Be watchful. Your adversary, the devil, walks around like a roaring lion, seeking whom he may devour. Withstand him steadfast in your faith… But may the God of all grace, who called you to his eternal glory by Christ Jesus, after you have suffered a little while, perfect, establish, strengthen, and settle you.', 'God of all grace will perfect and strengthen after suffering.', ['grace', 'strength', 'protection', 'hope', 'calling'], ['afraid', 'weary', 'suffering', 'hopeful'], ['devil', 'lion', 'withstand', 'grace', 'perfect', 'strengthen']),
]
