"""2 Timothy-like hope: precious promises, new creation"""
from catalog._entry import e

ENTRIES = [
    e('2 Peter', 1, 3, 4, 'Seeing that his divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us by his own glory and virtue, by which he has granted to us his precious and exceedingly great promises; that through these you may become partakers of the divine nature, having escaped from the corruption that is in the world by lust.', 'Precious promises; partakers of divine nature.', ['promise', 'holiness', 'calling', 'identity'], ['tempted', 'inadequate', 'hopeful'], ['power', 'precious', 'promises', 'partakers', 'divine nature']),
    e('2 Peter', 1, 10, 11, 'Therefore, brothers, be more diligent to make your calling and election sure. For if you do these things, you will never stumble. For thus you will be richly supplied with the entrance into the eternal Kingdom of our Lord and Savior, Jesus Christ.', 'Rich entrance into eternal Kingdom.', ['calling', 'kingdom', 'hope', 'eternal-life'], ['anxious', 'insecure', 'hopeful'], ['calling', 'election', 'stumble', 'Kingdom', 'entrance']),
    e('2 Peter', 3, 8, 9, 'But don’t forget this one thing, beloved, that one day is with the Lord as a thousand years, and a thousand years as one day. The Lord is not slow concerning his promise, as some count slowness; but he is patient with us, not wishing that anyone should perish, but that all should come to repentance.', 'Not slow; patient; not wishing any perish.', ['promise', 'patience', 'mercy', 'repentance', 'hope'], ['impatient', 'hopeless', 'hopeful'], ['slow', 'promise', 'patient', 'perish', 'repentance']),
    e('2 Peter', 3, 13, 13, 'But, according to his promise, we look for new heavens and a new earth, in which righteousness dwells.', 'New heavens and new earth promised.', ['hope', 'promise', 'new-beginning', 'righteousness'], ['hopeless', 'weary', 'hopeful'], ['new heavens', 'new earth', 'righteousness', 'promise']),
]
