"""1 John — fellowship, forgiveness, perfect love"""
from catalog._entry import e

ENTRIES = [
    e('1 John', 1, 5, 7, 'God is light, and in him is no darkness at all. If we say that we have fellowship with him and walk in the darkness, we lie and don’t tell the truth. But if we walk in the light as he is in the light, we have fellowship with one another, and the blood of Jesus Christ his Son, cleanses us from all sin.', 'Walk in light; blood cleanses from all sin.', ['light', 'forgiveness', 'holiness', 'unity'], ['guilty', 'lonely', 'hopeful'], ['light', 'darkness', 'fellowship', 'cleanses', 'sin']),
    e('1 John', 1, 8, 9, 'If we say that we have no sin, we deceive ourselves, and the truth is not in us. If we confess our sins, he is faithful and righteous to forgive us the sins and to cleanse us from all unrighteousness.', 'Confess; faithful to forgive and cleanse.', ['forgiveness', 'faithfulness', 'mercy', 'holiness'], ['guilty', 'shame', 'hopeful'], ['confess', 'faithful', 'forgive', 'cleanse', 'unrighteousness']),
    e('1 John', 2, 1, 2, 'My little children, I write these things to you so that you may not sin. If anyone sins, we have a Counselor with the Father, Jesus Christ, the righteous. And he is the atoning sacrifice for our sins, and not for ours only, but also for the whole world.', 'Counselor with the Father; atoning sacrifice.', ['forgiveness', 'salvation', 'presence', 'mercy'], ['guilty', 'afraid', 'hopeful'], ['Counselor', 'atoning', 'sins', 'world']),
    e('1 John', 2, 12, 12, 'I write to you, little children, because your sins are forgiven you for his name’s sake.', 'Sins forgiven for his name’s sake.', ['forgiveness', 'salvation'], ['guilty', 'hopeful', 'grateful'], ['sins', 'forgiven', 'name']),
    e('1 John', 2, 17, 17, 'The world is passing away with its lusts, but he who does God’s will remains forever.', 'Doer’s of God’s will remain forever.', ['eternal-life', 'holiness', 'hope'], ['anxious', 'worldly', 'hopeful'], ['world', 'passing', 'will', 'forever']),
    e('1 John', 2, 25, 25, 'This is the promise which he promised us, the eternal life.', 'Promise: eternal life.', ['eternal-life', 'promise', 'hope'], ['afraid', 'hopeless', 'hopeful'], ['promise', 'eternal life']),
    e('1 John', 3, 1, 2, 'See how great a love the Father has given to us, that we should be called children of God! For this cause the world doesn’t know us, because it didn’t know him. Beloved, now we are children of God. It is not yet revealed what we will be; but we know that when he is revealed, we will be like him, for we will see him just as he is.', 'Called children; we will be like him.', ['love', 'identity', 'hope', 'eternal-life'], ['lonely', 'rejected', 'loved', 'hopeful'], ['love', 'children', 'like him', 'see', 'revealed']),
    e('1 John', 3, 8, 8, 'He who sins is of the devil, for the devil has been sinning from the beginning. To this end the Son of God was revealed: that he might destroy the works of the devil.', 'Son revealed to destroy devil’s works.', ['victory', 'salvation'], ['afraid', 'bound', 'hopeful'], ['destroy', 'devil', 'works', 'revealed']),
    e('1 John', 3, 16, 16, 'By this we know love, because he laid down his life for us. And we ought to lay down our lives for the brothers.', 'He laid down his life for us.', ['love', 'salvation', 'compassion'], ['lonely', 'bitter', 'loved', 'hopeful'], ['love', 'laid down', 'life', 'brothers']),
    e('1 John', 3, 19, 20, 'And by this we know that we are of the truth and persuade our hearts before him, because if our heart condemns us, God is greater than our heart, and knows all things.', 'God greater than condemning heart.', ['comfort', 'identity', 'forgiveness'], ['guilty', 'condemned', 'anxious', 'hopeful'], ['heart', 'condemns', 'greater', 'knows']),
    e('1 John', 3, 21, 22, 'Beloved, if our hearts don’t condemn us, we have boldness toward God; so whatever we ask, we receive from him, because we keep his commandments and do the things that are pleasing in his sight.', 'Boldness; receive what we ask.', ['prayer', 'courage', 'holiness'], ['anxious', 'guilty', 'hopeful'], ['boldness', 'ask', 'receive', 'commandments']),
    e('1 John', 4, 4, 4, 'You are of God, little children, and have overcome them, because greater is he who is in you than he who is in the world.', 'Greater is he in you.', ['victory', 'presence', 'strength'], ['afraid', 'anxious', 'hopeful'], ['overcome', 'greater', 'in you', 'world']),
    e('1 John', 4, 7, 10, 'Beloved, let’s love one another, for love is of God; and everyone who loves has been born of God and knows God. He who doesn’t love doesn’t know God, for God is love. By this God’s love was revealed in us, that God has sent his only born Son into the world that we might live through him. In this is love, not that we loved God, but that he loved us, and sent his Son as the atoning sacrifice for our sins.', 'God is love; he loved us first.', ['love', 'salvation', 'identity'], ['lonely', 'unloved', 'guilty', 'loved', 'hopeful'], ['love', 'God is love', 'sent', 'Son', 'atoning']),
    e('1 John', 4, 16, 18, 'We know and have believed the love which God has for us. God is love, and he who remains in love remains in God, and God remains in him. In this, love has been made perfect among us, that we may have boldness in the day of judgment, because as he is, even so we are in this world. There is no fear in love; but perfect love casts out fear, because fear has punishment. He who fears is not made perfect in love.', 'Perfect love casts out fear.', ['love', 'fear', 'peace', 'presence'], ['afraid', 'anxious', 'lonely', 'loved', 'peaceful', 'hopeful'], ['love', 'perfect', 'casts out', 'fear', 'boldness']),
    e('1 John', 4, 19, 19, 'We love him, because he first loved us.', 'He first loved us.', ['love', 'identity'], ['unloved', 'lonely', 'loved', 'hopeful'], ['love', 'first loved']),
    e('1 John', 5, 4, 5, 'For whatever is born of God overcomes the world. This is the victory that has overcome the world: your faith. Who is he who overcomes the world, but he who believes that Jesus is the Son of God?', 'Faith overcomes the world.', ['victory', 'faithfulness', 'hope'], ['afraid', 'weary', 'hopeful'], ['overcomes', 'world', 'victory', 'faith', 'believes']),
    e('1 John', 5, 11, 13, 'The testimony is this: that God gave to us eternal life, and this life is in his Son. He who has the Son has the life. He who doesn’t have God’s Son doesn’t have the life. These things I have written to you who believe in the name of the Son of God, that you may know that you have eternal life.', 'Know that you have eternal life.', ['eternal-life', 'assurance', 'salvation', 'hope'], ['doubt', 'afraid', 'hopeful'], ['eternal life', 'Son', 'know', 'believe', 'written']),
    e('1 John', 5, 14, 15, 'This is the boldness which we have toward him, that if we ask anything according to his will, he listens to us. And if we know that he listens to us, whatever we ask, we know that we have the petitions which we have asked of him.', 'He listens; we have what we asked.', ['prayer', 'assurance', 'hope'], ['anxious', 'doubt', 'hopeful'], ['boldness', 'ask', 'will', 'listens', 'petitions']),
    e('1 John', 5, 18, 18, 'We know that whoever is born of God doesn’t sin, but he who was born of God keeps himself, and the evil one doesn’t touch him.', 'Kept; evil one doesn’t touch.', ['protection', 'holiness', 'identity'], ['afraid', 'tempted', 'hopeful'], ['born', 'keeps', 'evil one', 'touch']),
]
